import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGeneratedMigration1700000000000 implements MigrationInterface {
  name = 'AutoGeneratedMigration1700000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255), "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"), CONSTRAINT "UQ_permissions_name" UNIQUE ("name"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."roles_name_enum" AS ENUM('super_admin', 'administrator', 'user', 'shop_owner', 'shipper')`,
    );
    await queryRunner.query(
      `CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL DEFAULT 'user', "display_name" character varying(255), "description" text, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "image" character varying, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying, "discountPercent" integer, "code" character varying, CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."checkouts_status_enum" AS ENUM('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')`,
    );
    await queryRunner.query(
      `CREATE TABLE "checkouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "orderId" uuid, "amount" numeric(10,2) NOT NULL, "paymentMethod" character varying(50) NOT NULL, "paymentIntentId" uuid, "paymentUrl" character varying, "status" "public"."checkouts_status_enum" NOT NULL DEFAULT 'PENDING', "paymentDetails" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5800730d89f4137fc18770e4d4d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'confirmed', 'delivering', 'completed', 'canceled', 'processing_payment')`,
    );
    await queryRunner.query(
      `CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "total" integer, "note" character varying, "status" "public"."orders_status_enum" DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "date" character varying, "paymentMethod" character varying, "paymentDate" character varying, "isPaid" boolean NOT NULL DEFAULT false, "user_id" character varying(28), "restaurant_id" uuid, "promotion_id" uuid, "address_id" uuid, "shippingDetail_id" uuid, CONSTRAINT "REL_ccc7734f0a937b13277b0871f1" UNIQUE ("shippingDetail_id"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "orderDetails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "varity" character varying, "quantity" integer, "price" character varying, "note" character varying, "order_id" uuid, "food_id" uuid, CONSTRAINT "PK_11d407f307ebf19af9702464e22" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "foods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying, "image" character varying, "image_urls" text, "name" character varying, "price" numeric(10,2), "discount_percent" numeric(5,2), "sold_count" integer DEFAULT '0', "rating" numeric(3,2), "purchased_number" integer DEFAULT '0', "status" character varying, "tag" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "preparation_time" integer, "category_id" uuid, "restaurant_id" uuid, CONSTRAINT "PK_0cc83421325632f61fa27a52b59" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."restaurants_status_enum" AS ENUM('pending', 'approved', 'rejected')`,
    );
    await queryRunner.query(
      `CREATE TABLE "restaurants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying, "phoneNumber" character varying, "backgroundImage" character varying, "avatar" character varying, "description" character varying, "openTime" character varying, "closeTime" character varying, "licenseCode" character varying, "certificateImage" character varying, "status" "public"."restaurants_status_enum" NOT NULL DEFAULT 'pending', "latitude" numeric(10,7), "longitude" numeric(10,7), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "addressId" uuid, "owner_id" character varying(28), CONSTRAINT "REL_efe4eead3adf44a4649a3353ef" UNIQUE ("owner_id"), CONSTRAINT "PK_e2133a72eb1cc8f588f7b503e68" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "street" character varying NOT NULL, "ward" character varying NOT NULL, "district" character varying NOT NULL, "city" character varying NOT NULL, "latitude" double precision, "longitude" double precision, "isDefault" boolean, "label" character varying, "userId" character varying(28), CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."shipperCertificateInfos_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`,
    );
    await queryRunner.query(
      `CREATE TABLE "shipperCertificateInfos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cccd" character varying, "driverLicense" character varying, "status" "public"."shipperCertificateInfos_status_enum" NOT NULL DEFAULT 'PENDING', "verifiedAt" TIMESTAMP, "user_id" character varying(28), CONSTRAINT "REL_387abef374259557712a77cb4e" UNIQUE ("user_id"), CONSTRAINT "PK_10436575920f33cb43d0dc5313f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."users_authprovider_enum" AS ENUM('email', 'google', 'facebook')`,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("id" character varying(28) NOT NULL, "username" character varying NOT NULL, "password" character varying NOT NULL, "email" character varying, "name" character varying, "phone" character varying, "avatar" character varying, "is_active" boolean NOT NULL DEFAULT true, "birthday" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "lastLoginAt" TIMESTAMP, "authProvider" "public"."users_authprovider_enum" NOT NULL DEFAULT 'email', "google_id" character varying, "reset_password_token" character varying, "reset_password_expires" TIMESTAMP, "role_id" uuid, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "public"."shippingDetails_status_enum" AS ENUM('PENDING', 'SHIPPING', 'DELIVERED', 'CANCELLED', 'RETURNED', 'COMPLETED')`,
    );
    await queryRunner.query(
      `CREATE TABLE "shippingDetails" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."shippingDetails_status_enum", "estimatedDeliveryTime" TIMESTAMP, "actualDeliveryTime" TIMESTAMP, "trackingNumber" character varying, "user_id" character varying(28), "order_id" uuid, CONSTRAINT "REL_13e53d0d7574b6a266eb3bbdb8" UNIQUE ("order_id"), CONSTRAINT "PK_5eeb445b5f14fb3a7d7d9b7e6fb" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE TYPE "public"."reviews_type_enum" AS ENUM('food', 'shipper')`);
    await queryRunner.query(
      `CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" character varying, "comment" character varying, "rating" integer, "type" "public"."reviews_type_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" character varying(28), "food_id" uuid, "shipper_id" character varying(28), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying, "content" character varying, "receiveUser" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isRead" boolean DEFAULT false, "type" character varying, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "checkouts" ADD CONSTRAINT "FK_e077269fe39b9bff6f74c56bae1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "checkouts" ADD CONSTRAINT "FK_b272f8fea44c8fb5aaa0c3344cb" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_a922b820eeef29ac1c6800e826a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_85fdda5fcce2f397ef8f117a2c6" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_ef840932f45535891306fc3f327" FOREIGN KEY ("promotion_id") REFERENCES "promotions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_d39c53244703b8534307adcd073" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" ADD CONSTRAINT "FK_ccc7734f0a937b13277b0871f13" FOREIGN KEY ("shippingDetail_id") REFERENCES "shippingDetails"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orderDetails" ADD CONSTRAINT "FK_76d98794a8c9305943ad307b797" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "orderDetails" ADD CONSTRAINT "FK_42d9b70864bc878fdea951079c1" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "foods" ADD CONSTRAINT "FK_5152fefa8abc8a3bd6d284a404e" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "foods" ADD CONSTRAINT "FK_f9fecc8bb74f2a47b616c340163" FOREIGN KEY ("restaurant_id") REFERENCES "restaurants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "restaurants" ADD CONSTRAINT "FK_6ed5e37a5a3021bd177acb48ca5" FOREIGN KEY ("addressId") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "restaurants" ADD CONSTRAINT "FK_efe4eead3adf44a4649a3353efc" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "address" ADD CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shipperCertificateInfos" ADD CONSTRAINT "FK_387abef374259557712a77cb4e7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shippingDetails" ADD CONSTRAINT "FK_36214d9f8582fcedcddddab8737" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "shippingDetails" ADD CONSTRAINT "FK_13e53d0d7574b6a266eb3bbdb8a" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "reviews" ADD CONSTRAINT "FK_54dc24a848297dd66b8be101154" FOREIGN KEY ("food_id") REFERENCES "foods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "reviews" ADD CONSTRAINT "FK_610a2a4773705a24c5a4433257f" FOREIGN KEY ("shipper_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`,
    );
    await queryRunner.query(
      `ALTER TABLE "reviews" DROP CONSTRAINT "FK_610a2a4773705a24c5a4433257f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "reviews" DROP CONSTRAINT "FK_54dc24a848297dd66b8be101154"`,
    );
    await queryRunner.query(
      `ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shippingDetails" DROP CONSTRAINT "FK_13e53d0d7574b6a266eb3bbdb8a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "shippingDetails" DROP CONSTRAINT "FK_36214d9f8582fcedcddddab8737"`,
    );
    await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
    await queryRunner.query(
      `ALTER TABLE "shipperCertificateInfos" DROP CONSTRAINT "FK_387abef374259557712a77cb4e7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "address" DROP CONSTRAINT "FK_d25f1ea79e282cc8a42bd616aa3"`,
    );
    await queryRunner.query(
      `ALTER TABLE "restaurants" DROP CONSTRAINT "FK_efe4eead3adf44a4649a3353efc"`,
    );
    await queryRunner.query(
      `ALTER TABLE "restaurants" DROP CONSTRAINT "FK_6ed5e37a5a3021bd177acb48ca5"`,
    );
    await queryRunner.query(`ALTER TABLE "foods" DROP CONSTRAINT "FK_f9fecc8bb74f2a47b616c340163"`);
    await queryRunner.query(`ALTER TABLE "foods" DROP CONSTRAINT "FK_5152fefa8abc8a3bd6d284a404e"`);
    await queryRunner.query(
      `ALTER TABLE "orderDetails" DROP CONSTRAINT "FK_42d9b70864bc878fdea951079c1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orderDetails" DROP CONSTRAINT "FK_76d98794a8c9305943ad307b797"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" DROP CONSTRAINT "FK_ccc7734f0a937b13277b0871f13"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" DROP CONSTRAINT "FK_d39c53244703b8534307adcd073"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" DROP CONSTRAINT "FK_ef840932f45535891306fc3f327"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" DROP CONSTRAINT "FK_85fdda5fcce2f397ef8f117a2c6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "orders" DROP CONSTRAINT "FK_a922b820eeef29ac1c6800e826a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "checkouts" DROP CONSTRAINT "FK_b272f8fea44c8fb5aaa0c3344cb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "checkouts" DROP CONSTRAINT "FK_e077269fe39b9bff6f74c56bae1"`,
    );
    await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
    await queryRunner.query(`DROP TABLE "role_permissions"`);
    await queryRunner.query(`DROP TABLE "notifications"`);
    await queryRunner.query(`DROP TABLE "reviews"`);
    await queryRunner.query(`DROP TYPE "public"."reviews_type_enum"`);
    await queryRunner.query(`DROP TABLE "shippingDetails"`);
    await queryRunner.query(`DROP TYPE "public"."shippingDetails_status_enum"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TYPE "public"."users_authprovider_enum"`);
    await queryRunner.query(`DROP TABLE "shipperCertificateInfos"`);
    await queryRunner.query(`DROP TYPE "public"."shipperCertificateInfos_status_enum"`);
    await queryRunner.query(`DROP TABLE "address"`);
    await queryRunner.query(`DROP TABLE "restaurants"`);
    await queryRunner.query(`DROP TYPE "public"."restaurants_status_enum"`);
    await queryRunner.query(`DROP TABLE "foods"`);
    await queryRunner.query(`DROP TABLE "orderDetails"`);
    await queryRunner.query(`DROP TABLE "orders"`);
    await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
    await queryRunner.query(`DROP TABLE "checkouts"`);
    await queryRunner.query(`DROP TYPE "public"."checkouts_status_enum"`);
    await queryRunner.query(`DROP TABLE "promotions"`);
    await queryRunner.query(`DROP TABLE "categories"`);
    await queryRunner.query(`DROP TABLE "roles"`);
    await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
    await queryRunner.query(`DROP TABLE "permissions"`);
  }
}
